# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('archivo', models.FileField(upload_to='')),
                ('numeroVisto', models.IntegerField()),
                ('numeroBuscado', models.IntegerField()),
                ('fecha', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Usuario')),
            ],
        ),
    ]
