# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='archivo',
            field=models.FileField(upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
